export const CONVERSATIONS_FETCH_REQUEST = 'CONVERSATIONS_FETCH_REQUEST';
export const CONVERSATIONS_FETCH_SUCCESS = 'CONVERSATIONS_FETCH_SUCCESS';
export const CONVERSATIONS_FETCH_FAILURE = 'CONVERSATIONS_FETCH_FAILURE';

export const USERS_FETCH_REQUEST = 'USERS_FETCH_REQUEST';
export const USERS_FETCH_SUCCESS = 'USERS_FETCH_SUCCESS';
export const USERS_FETCH_FAILURE = 'USERS_FETCH_FAILURE';

export const STEPS_FETCH_REQUEST = 'STEPS_FETCH_REQUEST';
export const STEPS_FETCH_SUCCESS = 'STEPS_FETCH_SUCCESS';
export const STEPS_FETCH_FAILURE = 'STEPS_FETCH_FAILURE';
